//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusTicketBookingSystem.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.Text;

    public partial class Reservation
    {
        [DisplayName("Id")]
        public int ReservationId { get; set; }
        [DisplayName("Date")]
        public System.DateTime ReservationDate { get; set; }
        [DisplayName("Tour")]
        public int TourId { get; set; }
        [DisplayName("User name")]
        public string UserName { get; set; }
    
        public virtual Tour Tour { get; set; }

        public void ConfirmReservation(Reservation res, string to)
        {

        }
    }
}
