//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusTicketBookingSystem.Entities.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Seat
    {
        public int Id { get; set; }
        public bool IsAvailable { get; set; }
        public int SeatNumber { get; set; }
        public int PassengerId { get; set; }
        public Nullable<int> BusId { get; set; }
        public string Time { get; set; }
    
        public virtual Bus Bus { get; set; }
        public virtual Passenger Passenger { get; set; }
    }
}
