//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusTicketBookingSystem.Entities.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ticket
    {
        public int Id { get; set; }
        public string BookingTime { get; set; }
        public bool IsBlocked { get; set; }
        public int Trip_Id { get; set; }
        public Nullable<int> Passenger_Id { get; set; }
        public Nullable<decimal> Price { get; set; }
    
        public virtual Passenger Passenger { get; set; }
        public virtual Tour Tour { get; set; }
    }
}
